const list=document.getElementById('messageList');
const search=document.getElementById('messageSearch');
const platform=document.getElementById('platformFilter');
const sort=document.getElementById('sortFilter');
const detail=document.getElementById('detailPanel');
let activeFilter='all';
let activeConversation=null;
let inboxMessages=[];
let client=null;
let currentUser=null;

function escapeHtml(value=''){const div=document.createElement('div');div.textContent=value;return div.innerHTML}
function initials(name='?'){return name.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'?'}
function relativeTime(date){if(!date)return '';const seconds=Math.floor((Date.now()-new Date(date).getTime())/1000);if(seconds<60)return 'Just now';if(seconds<3600)return `${Math.floor(seconds/60)} min ago`;if(seconds<86400)return `${Math.floor(seconds/3600)} hr ago`;return new Date(date).toLocaleDateString()}
function typeFromCategory(category=''){const c=category.toLowerCase();if(c.includes('spam'))return 'spam';if(['sponsorship','collaboration','business','opportunity','partnership'].some(x=>c.includes(x)))return 'important';if(['question','content','relevant'].some(x=>c.includes(x)))return 'relevant';return 'general'}

async function loadInbox(){
  const {data:{user}}=await client.auth.getUser();
  if(!user){window.location.href='login.html';return}
  currentUser=user;
  const {data,error}=await client.from('messages').select('id,conversation_id,sender_id,platform,sender_name,sender_username,message_text,category,priority_score,relevance_score,is_read,is_spam,needs_reply,received_at,created_at,direction,sent_at').eq('user_id',user.id).eq('direction','incoming').order('received_at',{ascending:false});
  if(error){list.innerHTML=`<div class="no-results">Unable to load messages: ${escapeHtml(error.message)}</div>`;return}
  inboxMessages=(data||[]).map(m=>({...m,sender:m.sender_name||m.sender_username||'Unknown sender',priority:m.priority_score??0,relevance:m.relevance_score??0,type:m.is_spam?'spam':typeFromCategory(m.category),time:relativeTime(m.received_at||m.created_at),text:m.message_text}));
  renderList();
}
function filteredMessages(){const q=(search?.value||'').trim().toLowerCase();let items=inboxMessages.filter(m=>{const filterMatch=activeFilter==='all'||m.type===activeFilter;const platformMatch=platform?.value==='all'||m.platform===platform?.value;const textMatch=!q||`${m.sender} ${m.category||''} ${m.text}`.toLowerCase().includes(q);return filterMatch&&platformMatch&&textMatch});if(sort?.value==='recent')return items;return items.sort((a,b)=>b.priority-a.priority)}
function renderList(){if(!list)return;const items=filteredMessages();list.innerHTML=items.length?items.map(m=>`<article class="inbox-row ${activeConversation===m.id?'selected':''}" data-id="${m.id}" tabindex="0"><div class="sender-avatar">${initials(m.sender)}</div><div class="row-main"><div class="row-top"><strong>${escapeHtml(m.sender)}</strong><span class="platform">${escapeHtml(m.platform||'')}</span></div><p class="row-preview">${escapeHtml(m.text||'')}</p><span class="category-pill">${escapeHtml(m.category||'General')}</span></div><div class="row-side"><span class="score">${m.priority}</span><span class="row-time">${escapeHtml(m.time)}</span></div></article>`).join(''):'<div class="no-results">No messages yet. Connect a supported platform or add test messages to start using your inbox.</div>';list.querySelectorAll('.inbox-row').forEach(row=>{row.addEventListener('click',()=>showDetail(row.dataset.id));row.addEventListener('keydown',e=>{if(e.key==='Enter')showDetail(row.dataset.id)})})}

async function getConversation(message){if(message.conversation_id)return message.conversation_id;const {data,error}=await client.from('conversations').insert({user_id:currentUser.id,platform:message.platform||'Unknown',title:message.sender,last_message_at:message.received_at||message.created_at||new Date().toISOString()}).select('id').single();if(error)throw error;const {error:updateError}=await client.from('messages').update({conversation_id:data.id}).eq('id',message.id).eq('user_id',currentUser.id);if(updateError)throw updateError;message.conversation_id=data.id;return data.id}
async function loadThread(conversationId){const {data,error}=await client.from('messages').select('id,message_text,direction,created_at,received_at,sent_at,sender_name').eq('user_id',currentUser.id).eq('conversation_id',conversationId).order('created_at',{ascending:true});if(error)throw error;return data||[]}
function threadHtml(items){return items.map(item=>`<div class="thread-message ${item.direction==='outgoing'?'outgoing':'incoming'}"><div>${escapeHtml(item.message_text||'')}</div><small>${item.direction==='outgoing'?'You':escapeHtml(item.sender_name||'Sender')} · ${escapeHtml(relativeTime(item.sent_at||item.received_at||item.created_at))}</small></div>`).join('')}
async function showDetail(id){const m=inboxMessages.find(x=>String(x.id)===String(id));if(!m||!detail)return;activeConversation=m.id;renderList();detail.innerHTML=`<div class="detail-mobile-header"><button type="button" class="close-detail" id="closeDetail" aria-label="Close message">← <span>Back to inbox</span></button></div><div class="detail-head"><div><h3>${escapeHtml(m.sender)}</h3><p class="detail-meta">${escapeHtml(m.platform||'')} · ${escapeHtml(m.category||'General')} · ${escapeHtml(m.time)}</p></div><strong class="score">${m.priority}/100</strong></div><div class="conversation-thread" id="conversationThread"><div class="thread-loading">Loading conversation…</div></div><div class="analysis-grid"><div class="analysis-item"><small>Priority</small><strong>${m.priority}/100</strong></div><div class="analysis-item"><small>Relevance</small><strong>${m.relevance}/100</strong></div><div class="analysis-item"><small>Needs reply</small><strong>${m.needs_reply?'Yes':'No'}</strong></div><div class="analysis-item"><small>Category</small><strong>${escapeHtml(m.category||'General')}</strong></div></div><div class="reply-composer"><label for="replyText">Reply</label><textarea id="replyText" rows="4" placeholder="Write your reply…"></textarea><div class="reply-actions"><span id="replyStatus" class="reply-status">Replies are saved to Social AI Filter for now.</span><button class="primary send-reply" id="sendReply" type="button">Send Reply</button></div></div><div class="detail-actions"><button data-action="important">Mark Important</button><button data-action="spam">Mark as Spam</button></div>`;detail.classList.add('mobile-open');document.body.classList.add('detail-view-open');document.getElementById('closeDetail')?.addEventListener('click',closeDetail);
try{const conversationId=await getConversation(m);const thread=await loadThread(conversationId);document.getElementById('conversationThread').innerHTML=threadHtml(thread);detail.dataset.conversationId=conversationId}catch(error){document.getElementById('conversationThread').innerHTML=`<div class="thread-error">Unable to load conversation: ${escapeHtml(error.message)}</div>`}
document.getElementById('sendReply')?.addEventListener('click',()=>sendReply(m));detail.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{btn.textContent='Saved';btn.disabled=true}));}
async function sendReply(message){const input=document.getElementById('replyText');const button=document.getElementById('sendReply');const status=document.getElementById('replyStatus');const text=input?.value.trim();if(!text)return;if(!message.conversation_id){status.textContent='Conversation is still loading.';return}button.disabled=true;button.textContent='Saving…';status.textContent='Saving your reply…';const now=new Date().toISOString();const {error}=await client.from('messages').insert({user_id:currentUser.id,conversation_id:message.conversation_id,sender_id:message.sender_id||null,platform:message.platform||null,sender_name:currentUser.user_metadata?.full_name||currentUser.email,message_text:text,direction:'outgoing',sent_at:now,created_at:now});if(error){status.textContent=`Could not save reply: ${error.message}`;button.disabled=false;button.textContent='Send Reply';return}await client.from('conversations').update({last_message_at:now,updated_at:now}).eq('id',message.conversation_id).eq('user_id',currentUser.id);input.value='';status.textContent='Reply saved. Platform delivery is not connected yet.';button.disabled=false;button.textContent='Send Reply';const thread=await loadThread(message.conversation_id);const threadEl=document.getElementById('conversationThread');if(threadEl)threadEl.innerHTML=threadHtml(thread)}
function closeDetail(){detail?.classList.remove('mobile-open');document.body.classList.remove('detail-view-open')}
document.getElementById('filterTabs')?.addEventListener('click',e=>{const btn=e.target.closest('.filter-tab');if(!btn)return;document.querySelectorAll('.filter-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;renderList()});search?.addEventListener('input',renderList);platform?.addEventListener('change',renderList);sort?.addEventListener('change',renderList);
(async()=>{try{client=await ensureSupabaseLoaded();await loadInbox()}catch(error){if(list)list.innerHTML=`<div class="no-results">Inbox could not start: ${escapeHtml(error.message)}</div>`}})();
