const list=document.getElementById('messageList');
const search=document.getElementById('messageSearch');
const platform=document.getElementById('platformFilter');
const sort=document.getElementById('sortFilter');
const detail=document.getElementById('detailPanel');
const inboxTitle=document.getElementById('inboxTitle');
let activeFilter='all',activeConversation=null,inboxMessages=[],client=null,currentUser=null;
const titles={all:'All messages',smart:'Smart Priority',engaged:'Engaged Before',important:'Important messages',relevant:'Relevant messages',general:'General messages',spam:'Spam'};
function escapeHtml(value=''){const d=document.createElement('div');d.textContent=value??'';return d.innerHTML}
function initials(name='?'){return String(name??'?').split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'?'}
function relativeTime(date){if(!date)return '';const s=Math.floor((Date.now()-new Date(date).getTime())/1000);if(s<60)return 'Just now';if(s<3600)return `${Math.floor(s/60)} min ago`;if(s<86400)return `${Math.floor(s/3600)} hr ago`;return new Date(date).toLocaleDateString()}
function typeFromCategory(category){const c=String(category??'').toLowerCase();if(c.includes('spam'))return 'spam';if(['sponsorship','brand_deal','brand deal','collaboration','business','opportunity','partnership'].some(x=>c.includes(x)))return 'important';if(['question','content','feedback','relevant'].some(x=>c.includes(x)))return 'relevant';return 'general'}
function isSmart(m){return !!m.smart_priority_id||(m.priority_level==='high'||Number(m.priority_score??m.priority)>=75)}
function looksLikeOpportunity(text=''){return /\bsponsor(ship|ed)?\b|paid\s+(campaign|promotion|collab)|\bbrand\s+deal\b|\bcollaborat(e|ion|ing)\b|\bpartnership\b|\bcommercial\b|\bproposal\b|\bambassador\b/i.test(String(text??''))}
function needsClassification(m){const category=String(m.category??'').toLowerCase();const missing=!m.category||m.priority_score===null||m.priority_score===undefined||Number(m.priority_score)===0||!m.priority_level||m.relevance_score===null||m.relevance_score===undefined||Number(m.relevance_score)===0;const staleGeneral=category==='general'&&looksLikeOpportunity(m.message_text);return missing||staleGeneral}
async function classifyMessage(m){const {data:result,error:functionError}=await client.functions.invoke('classify-message',{body:{message:m.message_text,senderName:m.sender_name||m.sender_username,platform:m.platform}});if(functionError)throw new Error(functionError.message||'AI classification failed');if(!result)throw new Error('AI classification returned no result');if(result.error)throw new Error(result.error);const update={category:result.category||'general',priority_score:Number(result.priority_score)||0,priority_level:result.priority_level||'low',relevance_score:Number(result.relevance_score)||0,is_spam:!!result.is_spam};const {error}=await client.from('messages').update(update).eq('id',m.id).eq('user_id',currentUser.id);if(error)throw error;const optional={needs_reply:!!result.needs_reply};const optionalResult=await client.from('messages').update(optional).eq('id',m.id).eq('user_id',currentUser.id);if(optionalResult.error)console.info('Optional needs_reply field was not saved:',optionalResult.error.message);Object.assign(m,update,optional,{smart_priority_id:result.smart_priority_id??null,smart_priority_name:result.smart_priority_name??null});return m}
async function classifyPendingMessages(data){const pending=(data||[]).filter(m=>m.message_text&&needsClassification(m)).slice(0,10);for(const m of pending){try{await classifyMessage(m)}catch(error){console.error('Could not classify message',m.id,error);throw new Error(`AI could not process a message: ${error.message}`)}}}
async function loadInbox(){const {data:{user}}=await client.auth.getUser();if(!user){window.location.href='login.html';return}currentUser=user;const {data,error}=await client.from('messages').select('id,conversation_id,sender_id,platform,sender_name,sender_username,message_text,category,priority_score,priority_level,relevance_score,is_read,is_spam,needs_reply,received_at,created_at,direction,sent_at,senders(has_previous_engagement,engagement_count,last_engaged_at)').eq('user_id',user.id).order('received_at',{ascending:false});if(error){list.innerHTML=`<div class="no-results">Unable to load messages: ${escapeHtml(error.message)}</div>`;return}const incoming=(data||[]).filter(m=>!m.direction||m.direction==='incoming');await classifyPendingMessages(incoming);inboxMessages=incoming.map(m=>({...m,sender:m.sender_name||m.sender_username||'Unknown sender',priority:Number(m.priority_score)||0,relevance:Number(m.relevance_score)||0,type:m.is_spam?'spam':typeFromCategory(m.category),engaged:!!m.senders?.has_previous_engagement,time:relativeTime(m.received_at||m.created_at),text:m.message_text}));renderList()}
function filteredMessages(){const q=(search?.value||'').trim().toLowerCase();let items=inboxMessages.filter(m=>{const filterMatch=activeFilter==='all'||(activeFilter==='smart'&&isSmart(m))||(activeFilter==='engaged'&&m.engaged&&!isSmart(m))||(activeFilter!=='smart'&&activeFilter!=='engaged'&&m.type===activeFilter);const platformMatch=!platform||platform.value==='all'||m.platform===platform.value;const textMatch=!q||`${m.sender} ${m.category||''} ${m.text||''}`.toLowerCase().includes(q);return filterMatch&&platformMatch&&textMatch});return sort?.value==='recent'?items:items.sort((a,b)=>Number(b.priority)-Number(a.priority))}
function renderList(){if(!list)return;if(inboxTitle)inboxTitle.textContent=titles[activeFilter]||'Inbox';const items=filteredMessages();list.innerHTML=items.length?items.map(m=>`<article class="inbox-row ${activeConversation===m.id?'selected':''}" data-id="${m.id}" tabindex="0"><div class="sender-avatar">${initials(m.sender)}</div><div class="row-main"><div class="row-top"><strong>${escapeHtml(m.sender)}</strong><span class="platform">${escapeHtml(m.platform||'')}</span>${m.engaged&&!isSmart(m)?'<span class="engaged-badge">Engaged</span>':''}</div><p class="row-preview">${escapeHtml(m.text||'')}</p><span class="category-pill">${escapeHtml(m.smart_priority_name?`Smart Priority · ${m.smart_priority_name}`:isSmart(m)?'Smart Priority':m.engaged?'Engaged Before':m.category||'General')}</span></div><div class="row-side"><span class="score" title="Priority score">${m.priority}/100</span><span class="row-time">${escapeHtml(m.time)}</span></div></article>`).join(''):'<div class="no-results">No messages in this group yet.</div>';list.querySelectorAll('.inbox-row').forEach(r=>{r.addEventListener('click',()=>showDetail(r.dataset.id));r.addEventListener('keydown',e=>{if(e.key==='Enter')showDetail(r.dataset.id)})})}
async function getConversation(message){if(message.conversation_id)return message.conversation_id;const {data,error}=await client.from('conversations').insert({user_id:currentUser.id,platform:message.platform||'Unknown',title:message.sender,last_message_at:message.received_at||message.created_at||new Date().toISOString()}).select('id').single();if(error)throw error;const {error:updateError}=await client.from('messages').update({conversation_id:data.id}).eq('id',message.id).eq('user_id',currentUser.id);if(updateError)throw updateError;message.conversation_id=data.id;return data.id}
async function loadThread(id){const {data,error}=await client.from('messages').select('id,message_text,direction,created_at,received_at,sent_at,sender_name').eq('user_id',currentUser.id).eq('conversation_id',id).order('created_at',{ascending:true});if(error)throw error;return data||[]}
function threadHtml(items){return items.map(i=>`<div class="thread-message ${i.direction==='outgoing'?'outgoing':'incoming'}"><div>${escapeHtml(i.message_text||'')}</div><small>${i.direction==='outgoing'?'You':escapeHtml(i.sender_name||'Sender')} · ${escapeHtml(relativeTime(i.sent_at||i.received_at||i.created_at))}</small></div>`).join('')}
async function showDetail(id){const m=inboxMessages.find(x=>String(x.id)===String(id));if(!m||!detail)return;activeConversation=m.id;renderList();detail.innerHTML=`<div class="detail-mobile-header"><button type="button" class="close-detail" id="closeDetail">← <span>Back to inbox</span></button></div><div class="detail-head"><div><h3>${escapeHtml(m.sender)}</h3><p class="detail-meta">${escapeHtml(m.platform||'')} · ${escapeHtml(m.category||'General')} · ${escapeHtml(m.time)}</p>${m.smart_priority_name?`<p class="detail-smart-priority">Smart Priority: ${escapeHtml(m.smart_priority_name)}</p>`:''}</div><strong class="score">${m.priority}/100</strong></div><div class="conversation-thread" id="conversationThread"><div class="thread-loading">Loading conversation…</div></div><div class="analysis-grid"><div class="analysis-item"><small>Priority</small><strong>${m.priority}/100</strong></div><div class="analysis-item"><small>Priority level</small><strong>${escapeHtml(m.priority_level||'low')}</strong></div><div class="analysis-item"><small>Relevance</small><strong>${m.relevance}/100</strong></div><div class="analysis-item"><small>Engagement</small><strong>${m.engaged?'Engaged before':'New contact'}</strong></div></div><div class="reply-composer"><label for="replyText">Reply</label><textarea id="replyText" rows="4" placeholder="Write your reply…"></textarea><div class="reply-actions"><span id="replyStatus" class="reply-status">Replies are saved to Social AI Filter for now.</span><button class="primary send-reply" id="sendReply" type="button">Send Reply</button></div></div></div>`;detail.classList.add('mobile-open');document.body.classList.add('detail-view-open');document.getElementById('closeDetail')?.addEventListener('click',closeDetail);try{const cid=await getConversation(m);const thread=await loadThread(cid);document.getElementById('conversationThread').innerHTML=threadHtml(thread)}catch(error){document.getElementById('conversationThread').innerHTML=`<div class="thread-error">Unable to load conversation: ${escapeHtml(error.message)}</div>`}document.getElementById('sendReply')?.addEventListener('click',()=>sendReply(m))}
async function sendReply(m){const input=document.getElementById('replyText'),button=document.getElementById('sendReply'),status=document.getElementById('replyStatus'),text=input?.value.trim();if(!text)return;if(!m.conversation_id){status.textContent='Conversation is still loading.';return}button.disabled=true;button.textContent='Saving…';status.textContent='Saving your reply…';const now=new Date().toISOString();const {error}=await client.from('messages').insert({user_id:currentUser.id,conversation_id:m.conversation_id,sender_id:m.sender_id||null,platform:m.platform||null,sender_name:currentUser.user_metadata?.full_name||currentUser.email,message_text:text,direction:'outgoing',sent_at:now,created_at:now});if(error){status.textContent=`Could not save reply: ${error.message}`;button.disabled=false;button.textContent='Send Reply';return}if(m.sender_id){const {data:sender}=await client.from('senders').select('engagement_count').eq('id',m.sender_id).eq('user_id',currentUser.id).maybeSingle();const count=(sender?.engagement_count||0)+1;await client.from('senders').update({has_previous_engagement:true,engagement_count:count,last_engaged_at:now,updated_at:now}).eq('id',m.sender_id).eq('user_id',currentUser.id);m.engaged=true}await client.from('conversations').update({last_message_at:now,updated_at:now}).eq('id',m.conversation_id).eq('user_id',currentUser.id);input.value='';status.textContent='Reply saved. This contact is now marked as Engaged Before.';button.disabled=false;button.textContent='Send Reply';const thread=await loadThread(m.conversation_id);document.getElementById('conversationThread').innerHTML=threadHtml(thread);renderList()}
function closeDetail(){detail?.classList.remove('mobile-open');document.body.classList.remove('detail-view-open')}
document.getElementById('filterTabs')?.addEventListener('click',e=>{const b=e.target.closest('.filter-tab');if(!b)return;document.querySelectorAll('.filter-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderList()});search?.addEventListener('input',renderList);platform?.addEventListener('change',renderList);sort?.addEventListener('change',renderList);(async()=>{try{client=await ensureSupabaseLoaded();await loadInbox()}catch(error){if(list)list.innerHTML=`<div class="no-results">Inbox could not start: ${escapeHtml(error.message)}</div>`}})();