const opportunities=[];
const grid=document.getElementById('opportunityGrid');
const tabs=document.getElementById('oppsTabs');
let activeType='all';
function escapeHtml(value=''){const d=document.createElement('div');d.textContent=value??'';return d.innerHTML}
function normalizeType(category=''){const c=String(category).toLowerCase().replace(/[_-]/g,' ').trim();if(c.includes('sponsor'))return 'sponsorship';if(c.includes('brand deal'))return 'brand';if(c.includes('brand'))return 'brand';if(c.includes('collab'))return 'collaboration';if(c.includes('business')||c.includes('partnership')||c.includes('opportunity'))return 'business';return null}
function renderOpportunities(type=activeType){activeType=type;const items=opportunities.filter(o=>type==='all'||o.type===type);grid.innerHTML=items.length?items.map(o=>`<article class="opp-card"><div class="opp-top"><div class="opp-company"><div class="opp-icon">✦</div><div><strong>${escapeHtml(o.company)}</strong><small>${escapeHtml(o.platform||'Social')} · ${escapeHtml(o.label)}</small></div></div><span class="opp-score">${o.score}/100</span></div><h3>${escapeHtml(o.title)}</h3><p>${escapeHtml(o.text)}</p><div class="opp-bottom"><div><span class="opp-status ${o.status==='Reviewing'?'reviewing':''}">${escapeHtml(o.status)}</span><span class="opp-date"> · ${escapeHtml(o.date)}</span></div><div class="opp-actions"><button data-action="archive">Archive</button><button class="primary" data-action="review">Review</button></div></div></article>`).join(''):'<div class="no-opps">No opportunities yet. AI-detected sponsorships, brand deals, collaborations and business messages will appear here.</div>';
}
async function loadOpportunities(){try{const client=await ensureSupabaseLoaded();const {data:{user}}=await client.auth.getUser();if(!user){window.location.href='login.html';return}const {data,error}=await client.from('messages').select('id,sender_name,sender_username,platform,message_text,category,priority_score,priority_level,received_at,created_at,direction,is_spam').eq('user_id',user.id).order('received_at',{ascending:false});if(error)throw error;opportunities.length=0;(data||[]).filter(m=>(!m.direction||m.direction==='incoming')&&!m.is_spam).forEach(m=>{const type=normalizeType(m.category);if(!type)return;const label={sponsorship:'Sponsorship',brand:'Brand Deal',collaboration:'Collaboration',business:'Business'}[type]||'Opportunity';const company=m.sender_name||m.sender_username||'Unknown sender';opportunities.push({id:m.id,type,label,company,platform:m.platform||'Social',score:m.priority_score??0,title:`${label} opportunity`,text:m.message_text||'',status:'New',date:new Date(m.received_at||m.created_at||Date.now()).toLocaleDateString()})});renderOpportunities(activeType)}catch(error){grid.innerHTML=`<div class="no-opps">Unable to load opportunities: ${escapeHtml(error.message)}</div>`}}
tabs?.addEventListener('click',e=>{const b=e.target.closest('.opp-tab');if(!b)return;document.querySelectorAll('.opp-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderOpportunities(b.dataset.type)});
loadOpportunities();